import Provider from "@/components/Provider";
import { GlobalStyle } from "@/styles/GlobalStyle";
import FooterPlayer from "@/components/audio/FooterPlayer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Provider>
          <GlobalStyle />
          {/* <RecoilRoot> */}
          {children}
          <FooterPlayer />
          {/* </RecoilRoot> */}
        </Provider>
      </body>
    </html>
  );
}
